### ISSUE TITLE
memory challenge when deal with multigroups data

### ISSUE THREAD

**Issue by chichizhao** [mayukhmondal/ABC-DLS#4]
Hello Dr. Mayukh Mondal,
I extend my gratitude for providing the invaluable ABC-DLS tools. While utilizing them, I encountered a challenge with multigroups data. The system indicated a requirement of 1.45 TB memory, whereas our lab computer is equipped with only 500 GB. To address this, I proposed merging two closely related groups into one, anticipating a resolution.
> numpy.core._exceptions._ArrayMemoryError: Unable to allocate 1.45 TiB for an array with shape (25, 27, 19, 17, 21, 27, 49, 33) and data type int64

My query pertains to the potential reduction in memory usage by consolidating two groups. I am eager to hear your insights and suggestions on this matter. Your expertise is highly valued, and I sincerely appreciate your guidance.
Thank you!
Best regards,
Chichi

**Comment by mayukhmondal** [comment]
Hi Chichi,
               It is difficult to say why you are reaching such a high memory without knowing the command that you are using. 
By default ABC-DLS run the whole thing on the RAM but you can force it to run on HD using h5 data format and use less memory. To use it for your data use simply --chunksize 10000. Lower the number of chuksize in case it still fails. You can go as low as --chunksize 1. This will slow the preprocessing but will use less memory.
Hope this helps. 
Cheers,
Dr. Mayukh Mondal

**Comment by chichizhao** [comment]
Hi! Dr. Mayukh Mondal,
Thank you for your advice, and I'm still grappling with the issue. Here are more details about my problem. I'm having difficulty comprehending it fully, and below you'll find the bash command line and the corresponding output information:
I would greatly appreciate any further assistance or clarification you can provide on this matter.
Best~ 
Chichi

> python /home/chichi/softwares/ABC-DLS/src/SFS/Run_VCF2SFS.py --popfile Input2.csv --sfs_pop TKS,HTB,Xu4217,NRT,Xu291,TM,QTH,MID --chunksize 1000 example.aa.vcf.gz
Traceback (most recent call last):
  File "/home/chichi/softwares/ABC-DLS/src/SFS/Run_VCF2SFS.py", line 34, in <module>
    out = VCF2SFS(vcffile=args.vcffile, popfile=args.popfile,
  File "/home/chichi/softwares/ABC-DLS/src/SFS/Class.py", line 39, in __new__
    return cls.wrapper(vcffile=vcffile, popfile=popfile, sfs_pop=sfs_pop, chunk_length=chunk_length, out=out)
  File "/home/chichi/softwares/ABC-DLS/src/SFS/Class.py", line 64, in wrapper
    sfs = cls.vcf2sfs(vcf=vcffile, fs_shape=fs_shape, sfs_pop=sfs_pop, subpopdict=subpopdict,
  File "/home/chichi/softwares/ABC-DLS/src/SFS/Class.py", line 134, in vcf2sfs
    sfs = numpy.zeros(fs_shape, numpy.int_)
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 1.45 TiB for an array with shape (25, 27, 19, 17, 21, 27, 49, 33) and data type int64

**Comment by mayukhmondal** [comment]
Ok. Now I see. It looks like indeed you have a too big SFS. For example your current SFS would have in total 199,893,822,975
or 200 billion elements (25*27*19...) which might not be practical to train. SFS has a problem, it becomes impractical easily when we increase the sample size and population number. I will suggest keeping the number of cells close to 100 thousand to make it work (I would have implemented a sparse matrix but I found it does not help anyway with a high number of cells for SFS thus not implemented). Generally I have seen it lose power more than 100k elements. For example you can use 2 individuals per population for your particular SFS (and then create multiple SFS files to use it for more robust results), and merge some populations together or use separate two different models (depending on your question).

**Comment by chichizhao** [comment]
I sincerely appreciate your guidance, and I'm pleased to share that reducing the number of individuals per population has proven effective in addressing the analysis problem.
Best~
Chichi
